<a href="https://colab.research.google.com/github/SabalNiroula/Colab-files/blob/master/Tensorflow_fundamentals_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This is my first google colab doc for learning **Tensorflow**





In [1]:
# import tensorflow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.9.2


![link text](https://camo.githubusercontent.com/c389e3b3abc7e30e0e49b22a3899b349d8332d30e4d87c533f9ef71ee15c3da3/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f74656e736f72666c6f772d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67)

In [2]:
# creating your first tensor
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# checking the number of dimension of scalar
scalar.ndim

0

In [4]:
# Creating the vector
vector = tf.constant([10, 10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Creating matrix (Which has more than 1 dimension)
matrix = tf.constant([[10, 20],
                      [20, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 20.],
                              [20., 30.],
                              [30., 20.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 20.],
       [20., 30.],
       [30., 20.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
matrixx = tf.constant([[[1,2],
                        [2,1]],
                        [[2,3],
                        [3,2]],
                        [[3,4],
                        [4,3]]], dtype=tf.int16)
matrixx

<tf.Tensor: shape=(3, 2, 2), dtype=int16, numpy=
array([[[1, 2],
        [2, 1]],

       [[2, 3],
        [3, 2]],

       [[3, 4],
        [4, 3]]], dtype=int16)>

In above there are 3 (2-D) array, 2D array have 2 rows, those rows have 2 element. Hence, shape of (3,2,2)

In [11]:
matrixx.ndim

3

### **----------------------------------------------------------------------------**


## Creating tensor with tf.Variable
## With tf.variable we can create changeable tensors which with constant would not be changed

In [12]:
changeable_tensor = tf.Variable([10, 20])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [13]:
# to change values we use assign function like this:
changeable_tensor[0].assign(21408)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21408,    20], dtype=int32)>

### **-----------------------------------------------------------------------------------------**


### Creating random tensors 

In [14]:
random1 = tf.random.Generator.from_seed(32)
random1 = random1.normal(shape = (3, 2))

random2 = tf.random.Generator.from_seed(32)
random2 = random2.normal(shape=(3,2))

random1, random2, random1 == random2

## Here the seed is a number for random number generator. normal here means normal distribution 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.15898712,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.15898712,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### **-----------------------------------------------------------------------------------------**


## Shuffling the order of tensors 

In [15]:
not_shuffled = tf.constant([[10, 20],
                            [20, 30],
                           [30, 40]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int32)>

In [16]:
# setting global and operation level seed ensure the tensor to be shuffled but it will be shuffled at same order everytime because both seed are same
tf.random.set_seed(22) # global random seed
tf.random.shuffle(not_shuffled, seed = 20) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int32)>

### **-----------------------------------------------------------------------------------------**



## Other ways to create tensor

In [17]:
# making tensors of ones
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [18]:
tf.zeros((3,4), tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [19]:
numpy_arr = np.arange(1, 25)
numpy_arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
A = tf.constant(numpy_arr, shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

#**-----------------------------------------------------------------------------------------**


# Getting information about tensors 
when dealing with tensors you probably want to be aware of this attributes:
- Shape
- Rank
- Axis or Dimension
- Size

In [21]:
# create a rank 4 dimension
rank_4 = tf.ones(shape=[2,3,4,5], dtype=tf.dtypes.int32)
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [22]:
rank_4[0][0] # if we specify rank[0] it will bring me first 3D array and specifying again 0 will will bring me first 2D array within 3D array

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [23]:
# Now let's get shape, size and the dimension of the rank_4 tensor
rank_4.shape, tf.size(rank_4), rank_4.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [24]:
#Get various attributes of tensor
print("Datatypes of every element:", rank_4.dtype)
print("Dimension of tensor:", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Total size of tensor:", tf.size(rank_4))
print("Total size of tensor:", tf.size(rank_4).numpy())
print("Element of 0th axis :", rank_4[0])

Datatypes of every element: <dtype: 'int32'>
Dimension of tensor: 4
Shape of tensor: (2, 3, 4, 5)
Total size of tensor: tf.Tensor(120, shape=(), dtype=int32)
Total size of tensor: 120
Element of 0th axis : tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(3, 4, 5), dtype=int32)


#**-----------------------------------------------------------------------------------------**





# Indexing Tensors
Tensors can be indexed just like python list.

In [25]:
# Get first two element of each dimension
rank_4[:2, :2, :2, :2] # since multiple dimension we separate them by colon

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int32)>

In [26]:
# Creating rank 2 tensor
rank_2 = tf.zeros(shape = (3,4))
rank_2
# get the last item of each row
print(rank_2[:, -1])

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [27]:
rank_2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
# Adding extra dimension to our rank_2 tensor
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [29]:
# Alternative also the best way to do :
print(tf.expand_dims(rank_2, axis = 0)) # adds extra dimension at the 2D
print(tf.expand_dims(rank_2, axis = 1)) # adds extra dimension at the second or 1D
print(tf.expand_dims(rank_2, axis = -1)) # adds extra dimension at the element

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 3, 4), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]], shape=(3, 1, 4), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]]], shape=(3, 4, 1), dtype=float32)


#**-----------------------------------------------------------------------------------------**

# Manipulating Tensors
**Basic operation** 

`+`, `-`, `/`, `*`

In [30]:
tensor = tf.constant([[10, 20], [20, 30]])
print(tensor+10) # is same as 
print(tf.math.add(tensor, 10))


tf.Tensor(
[[20 30]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 30]
 [30 40]], shape=(2, 2), dtype=int32)


In [31]:
print(tensor*10) # is same as 
print(tf.math.multiply(tensor, 10))


tf.Tensor(
[[100 200]
 [200 300]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [200 300]], shape=(2, 2), dtype=int32)


#**-----------------------------------------------------------------------------------------**


# Matrix Multiplication

In [32]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [33]:
# for matrix multiplication using tensorflow use this:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 500,  800],
       [ 800, 1300]], dtype=int32)>

In [34]:
# same operation can be done in python using "@" operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 500,  800],
       [ 800, 1300]], dtype=int32)>

In [35]:
# making two (3, 2) tensor
X = tf.constant( np.random.randint(100, size=6), shape=(3,2))
print(X)

Y = tf.constant(np.random.randint(1,10, 6), shape= (3,2))
print(Y)

tf.Tensor(
[[83 80]
 [31 46]
 [26 23]], shape=(3, 2), dtype=int64)
tf.Tensor(
[[8 3]
 [2 9]
 [1 7]], shape=(3, 2), dtype=int64)


In [37]:
(X) @ Y

InvalidArgumentError: ignored

### Error raised because column of tensor1 must equal row of tensor2. let's change their shape 


In [38]:
# Now let's do matrix multiplication again
tf.reshape(X, shape=(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 855, 1186],
       [ 443,  533]])>

In [39]:
# can use transpose to change row into columns too but see the DIFFERENCE
Y, tf.transpose(Y), tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[8, 3],
        [2, 9],
        [1, 7]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[8, 2, 1],
        [3, 9, 7]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[8, 3, 2],
        [9, 1, 7]])>)

#**-----------------------------------------------------------------------------------------**


# The Dot Product
matrix multiplication is often referred to as dot product.

you can perform matrix multiplication using: 
- `tf.matmul()`
- `tf.tensordot()`

In [40]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[83, 80],
        [31, 46],
        [26, 23]])>, <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[8, 3],
        [2, 9],
        [1, 7]])>)

In [41]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[752, 710],
       [755, 815]])>

In [42]:
# perform dot matrix on x on y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes= 1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[752, 710],
       [755, 815]])>

In [43]:
# perform matrix multiplication on X and Y (Transposed)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[904, 886, 643],
       [386, 476, 353],
       [277, 259, 187]])>

#**-----------------------------------------------------------------------------------------**


# converting the datatypes of tensors

In [44]:
# let's create tensor and check their datatype
A = tf.constant([10, 20])
A.dtype

tf.int32

In [45]:
B = tf.constant([20.9, 30.5])
B.dtype

tf.float32

In [46]:
# Nvidia gpus run faster in float16 than in float32
# let's reduce the precision from 32 to 16 
# it is reducing hardware memory from taking 32 bits to 16 bits making it faster
new_B = tf.cast(B, dtype=tf.float16)
new_B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([20.9, 30.5], dtype=float16)>

In [47]:
# lets convert int32 to float 32
C = tf.cast(A, dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 20.], dtype=float32)>

#**-----------------------------------------------------------------------------------------**


# Aggregating tensors
Aggregating tensors = converting them from multiple values down to a smaller amount of value.

In [48]:
D = tf.constant([-12, -23, 34, 56, 75, 53, 66, 3, 93])
D

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([-12, -23,  34,  56,  75,  53,  66,   3,  93], dtype=int32)>

In [49]:

D = tf.abs(D)
D

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([12, 23, 34, 56, 75, 53, 66,  3, 93], dtype=int32)>

Let's practice some of the aggregation that are:
- Get the minimum and maximum value of tensor
- Get the mean of tensor
-Get the sum of tensor 

In [50]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [51]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=93>

In [52]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [53]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=415>

In [54]:
tf.math.reduce_std(tf.cast(D, dtype=tf.float32)) # calculate standard deviation|

<tf.Tensor: shape=(), dtype=float32, numpy=28.434895>

In [55]:
tf.math.reduce_variance(tf.cast(D, dtype=tf.float32)) # calculate variance

<tf.Tensor: shape=(), dtype=float32, numpy=808.5432>

## Finding the positional maximum and minimum

In [56]:
tf.random.set_seed(42)
A = tf.random.uniform(shape=[50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [57]:
# using argmax which returns the index of highest value
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [58]:
A[tf.math.argmax(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [59]:
assert A[tf.math.argmax(A)] == tf.reduce_max(A)

In [60]:
# finding the argmin of tensor A
tf.math.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

#**-----------------------------------------------------------------------------------------**


## Squeezing our tensor(removing all single dimensions)

In [61]:
G = tf.random.uniform(shape=[1, 1, 1, 23]) 

In [62]:
G.shape

TensorShape([1, 1, 1, 23])

In [63]:
G_squeezed = tf.squeeze(G) # here squeeziing will remove all the unnecessary 1D array which can be seen in below output:
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(23,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 ], dtype=float32)>,
 TensorShape([23]))

# One hot encoding
One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

![](https://i.stack.imgur.com/FQIlT.jpg)
0 indicates non existent while 1 indicates existent.

`Why do you need one hot encoding?`

*Problem with label encoding* is that it assumes higher the categorical value, better the category. “Wait, What!?”.

**Let me explain**: What this form of organization presupposes is VW > Acura > Honda based on the categorical values. Say supposing your model internally calculates average, then accordingly we get, 1+3 = 4/2 =2. This implies that: Average of VW and Honda is Acura. This is definitely a recipe for disaster. This model’s prediction would have a lot of errors.

In [64]:
# let's create a list of indices
some_list = [1, 2, 3, 4, 5]

# One hode encode our list
tf.one_hot(some_list, depth= 5) # output = 5(len(some_list)) * 4
# depth will make the 1D array of len = depth i.e. specified above 

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Tensorflow interacts beautifully with numpy array

In [65]:
# Create tensor from numpy array
J = tf.constant(np.array([10., 324., 43., 123.,]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 10., 324.,  43., 123.])>

In [66]:
# create numpy array from tensor
np.array(J), type(np.array(J))

(array([ 10., 324.,  43., 123.]), numpy.ndarray)

## Finding access to GPUs

In [67]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [68]:
!nvidia-smi

Mon Jan  2 10:22:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    32W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------